Match User auto-plus3-tunnel
    AuthenticationMethods publickey
    PasswordAuthentication no
    PubkeyAuthentication yes
    AllowTcpForwarding yes
    AllowAgentForwarding no
    AllowStreamLocalForwarding no
    GatewayPorts no
    PermitOpen 127.0.0.1:18083 127.0.0.1:8791 127.0.0.1:8893 127.0.0.1:18765 127.0.0.1:8788 127.0.0.1:8008 127.0.0.1:8720 127.0.0.1:8789 127.0.0.1:18097
    PermitListen 127.0.0.1:18003
    PermitTunnel no
    PermitTTY no
    X11Forwarding no
    MaxSessions 0
