"""Service client for payment links generated by openai-pay-long-link.

The long-link service owns proxy credentials and payment execution. Auto-GPT
adds only safe task overrides such as Team business fields and the mandatory
Team checkout proxy country, then persists the redacted versioned API result.
"""

from __future__ import annotations

import hashlib
import os
import re
import threading
import time
import urllib.parse
from datetime import datetime, timezone
from typing import Any, Callable, Iterable

import requests

from services.chatgpt_core.payment_link_cache import (
    PAYMENT_LINK_GENERATION_TEAM,
    PAYMENT_LINK_PLAN_TEAM,
    extract_payment_link_qr_expires_at,
    normalize_payment_link_expiry_source,
    normalize_payment_link_expires_at,
    normalize_payment_link_type,
    payment_link_type_from_payload,
    payment_link_variant_key,
)


DEFAULT_BASE_URL = "http://openai-pay-long-link:8788"
DEFAULT_REQUEST_TIMEOUT_SECONDS = 20.0
DEFAULT_PROFILE_CACHE_SECONDS = 30.0
UPI_QR_VALIDITY_SECONDS = 5 * 60
UPI_QR_EXPIRY_TOLERANCE_SECONDS = 60

_V1_PROFILE_PATH = "/api/v1/payment-links/profile"
_V1_BATCH_PATH = "/api/v1/payment-links/batches"
_V1_BATCH_STATUS_PATH = "/api/v1/payment-links/batches/{batch_id}"
_LEGACY_PROFILE_PATH = "/api/internal/payment-links/profile"
_LEGACY_BATCH_PATH = "/api/internal/payment-links/batches"
_LEGACY_BATCH_STATUS_PATH = "/api/internal/payment-links/batches/{batch_id}"
_API_MODE_V1 = "v1"
_API_MODE_LEGACY = "legacy"
_RUNNING_STATUSES = {"queued", "running"}
_TERMINAL_STATUSES = {"done", "error", "interrupted"}
_JWT_RE = re.compile(r"\beyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+(?:\.[A-Za-z0-9_-]+)?\b")
_profile_cache_lock = threading.Lock()
_profile_cache: dict[tuple[str, str, str], tuple[float, dict[str, Any]]] = {}


class LongLinkPaymentError(RuntimeError):
    """Raised when the generic payment-link service API cannot be used."""


def _env_float(name: str, default: float, *, minimum: float) -> float:
    try:
        value = float(str(os.getenv(name) or default).strip())
    except (TypeError, ValueError):
        value = default
    return max(value, minimum)


def _safe_error_text(value: Any, *, secrets: Iterable[str] = ()) -> str:
    text = str(value or "").strip()
    for secret in secrets:
        normalized = str(secret or "")
        if normalized:
            text = text.replace(normalized, "***")
    text = _JWT_RE.sub("***", text)
    return text[:500]


def _http_url(value: Any) -> str:
    url = str(value or "").strip()
    if not url or len(url) > 10_000 or any(ord(character) < 32 or ord(character) == 127 for character in url):
        return ""
    try:
        parsed = urllib.parse.urlsplit(url)
    except ValueError:
        return ""
    if parsed.scheme.lower() not in {"http", "https"} or not parsed.netloc:
        return ""
    return url


def normalize_long_link_base_url(value: Any) -> str:
    """Validate a service base URL without accepting credentials or URL suffix data."""

    raw = str(value or "").strip().rstrip("/")
    if not raw:
        raise LongLinkPaymentError("未配置支付链接生成服务地址")
    if len(raw) > 2048 or any(ord(character) < 32 or ord(character) == 127 for character in raw):
        raise LongLinkPaymentError("支付链接生成服务地址格式无效")
    try:
        parsed = urllib.parse.urlsplit(raw)
        port = parsed.port
    except ValueError as exc:
        raise LongLinkPaymentError("支付链接生成服务地址格式无效") from exc
    if (
        parsed.scheme.lower() not in {"http", "https"}
        or not parsed.hostname
        or parsed.username is not None
        or parsed.password is not None
        or parsed.query
        or parsed.fragment
    ):
        raise LongLinkPaymentError("支付链接生成服务地址必须是无凭据、无查询参数的 HTTP(S) URL")
    hostname = parsed.hostname
    if ":" in hostname and not hostname.startswith("["):
        hostname = f"[{hostname}]"
    netloc = hostname
    if port is not None:
        netloc = f"{netloc}:{port}"
    path = parsed.path.rstrip("/")
    return urllib.parse.urlunsplit((parsed.scheme.lower(), netloc, path, "", ""))


def _runtime_config_value(config_key: str, env_key: str, default: str = "") -> str:
    configured = ""
    try:
        from core.config_store import config_store

        configured = str(config_store.get(config_key, "") or "").strip()
    except Exception:
        configured = ""
    return configured or str(os.getenv(env_key) or default).strip()


def _iso_timestamp(value: Any) -> str:
    try:
        timestamp = float(value)
    except (TypeError, ValueError):
        return ""
    if timestamp <= 0:
        return ""
    try:
        return datetime.fromtimestamp(timestamp, timezone.utc).isoformat()
    except (OverflowError, OSError, ValueError):
        return ""


def normalize_payment_profile(profile_response: dict[str, Any] | None) -> dict[str, Any]:
    response = profile_response if isinstance(profile_response, dict) else {}
    profile = response.get("profile") if isinstance(response.get("profile"), dict) else {}
    profile_hash = str(response.get("profile_hash") or profile.get("profile_hash") or "").strip()
    link_type = str(response.get("link_type") or profile.get("link_type") or "hosted").strip().lower() or "hosted"
    country = str(profile.get("billing_country") or profile.get("country") or "").strip().upper()
    currency = str(profile.get("currency") or "").strip().upper()
    try:
        effective_concurrency = int(response.get("effective_concurrency") or profile.get("effective_concurrency") or 0)
    except (TypeError, ValueError):
        effective_concurrency = 0
    normalized = {
        "profile_hash": profile_hash,
        "link_type": link_type,
        "country": country,
        "currency": currency,
        "checkout_ui_mode": str(profile.get("checkout_ui_mode") or "").strip().lower(),
        "effective_concurrency": max(effective_concurrency, 0),
        "profile": dict(profile),
    }
    # Keep the redacted Team business summary returned by the long-link
    # profile endpoint.  Raw promo codes are never accepted here.
    team = profile.get("team") if isinstance(profile.get("team"), dict) else profile.get("team_plan_data")
    if isinstance(team, dict):
        normalized["team"] = dict(team)
        normalized["team_plan_data"] = dict(team)
    regions = profile.get("regions") if isinstance(profile.get("regions"), dict) else {}
    if regions:
        normalized["regions"] = dict(regions)
    for key in ("plan", "plan_name", "generation_kind", "promo_code_digest", "variant_key"):
        value = response.get(key)
        if value in (None, ""):
            value = profile.get(key)
        if value not in (None, ""):
            normalized[key] = value
    if "team" in normalized:
        normalized.setdefault("plan", PAYMENT_LINK_PLAN_TEAM)
        normalized.setdefault("generation_kind", PAYMENT_LINK_GENERATION_TEAM)
        normalized.setdefault("plan_name", "chatgptteamplan")
    return normalized


def payment_link_from_remote_job(
    job: dict[str, Any],
    *,
    profile: dict[str, Any],
) -> dict[str, Any]:
    """Validate and normalize a completed generic long-link response."""

    payload = job if isinstance(job, dict) else {}
    result = payload.get("result") if isinstance(payload.get("result"), dict) else {}
    url = ""
    for key in ("url", "provider_redirect_url", "long_url", "stripe_redirect_url", "stripe_hosted_url"):
        url = _http_url(result.get(key))
        if url:
            break
    if not url:
        raise LongLinkPaymentError("支付链接任务成功但未返回有效 HTTP(S) 链接")

    explicit_link_type = normalize_payment_link_type(result.get("link_type") or profile.get("link_type"))
    method_link_type = normalize_payment_link_type(
        result.get("payment_method_type") or profile.get("payment_method_type")
    )
    inferred_link_type = payment_link_type_from_payload({**profile, **result, "url": url})
    link_type = inferred_link_type or explicit_link_type or method_link_type or "hosted"
    raw_generation_kind = str(
        result.get("generation_kind") or profile.get("generation_kind") or ""
    ).strip().lower()
    raw_plan = str(result.get("plan") or profile.get("plan") or "").strip().lower()
    raw_plan_name = str(result.get("plan_name") or profile.get("plan_name") or "").strip().lower()
    is_team = (
        link_type in {"team", "team_checkout"}
        or raw_plan in {"team", "team_checkout", "chatgptteamplan"}
        or raw_generation_kind == PAYMENT_LINK_GENERATION_TEAM
        or raw_plan_name == "chatgptteamplan"
    )
    if is_team:
        link_type = "team"
    team_source = result.get("team_plan_data") if isinstance(result.get("team_plan_data"), dict) else {}
    if not team_source and isinstance(result.get("team"), dict):
        team_source = result.get("team")
    if not team_source and isinstance(profile.get("team"), dict):
        team_source = profile.get("team")
    if not team_source and isinstance(profile.get("team_plan_data"), dict):
        team_source = profile.get("team_plan_data")
    team_plan_data = {
        "workspace_name": str(team_source.get("workspace_name") or team_source.get("workspaceName") or "").strip(),
        "price_interval": str(team_source.get("price_interval") or team_source.get("priceInterval") or "month").strip().lower(),
        "seat_quantity": team_source.get("seat_quantity") or team_source.get("seatQuantity") or 2,
        "cancel_url": str(team_source.get("cancel_url") or team_source.get("cancelUrl") or "").strip(),
    } if is_team else {}
    if is_team:
        try:
            team_plan_data["seat_quantity"] = int(team_plan_data["seat_quantity"])
        except (TypeError, ValueError):
            team_plan_data["seat_quantity"] = 2
    profile_hash = str(payload.get("profile_hash") or profile.get("profile_hash") or "").strip()
    profile_detail = profile.get("profile") if isinstance(profile.get("profile"), dict) else {}
    profile_regions = profile.get("regions") if isinstance(profile.get("regions"), dict) else profile_detail.get("regions")
    profile_regions = profile_regions if isinstance(profile_regions, dict) else {}
    checkout_ui_mode = str(
        result.get("checkout_ui_mode")
        or profile.get("checkout_ui_mode")
        or profile_detail.get("checkout_ui_mode")
        or ""
    ).strip().lower()
    checkout_proxy_region = str(
        result.get("checkout_proxy_region")
        or profile.get("checkout_proxy_region")
        or profile_regions.get("checkout")
        or ""
    ).strip().upper()
    promo_code_digest = str(
        result.get("promo_code_digest") or profile.get("promo_code_digest") or team_source.get("promo_code_digest") or ""
    ).strip()
    if is_team and promo_code_digest:
        team_plan_data["promo_code_digest"] = promo_code_digest
    plan = PAYMENT_LINK_PLAN_TEAM if is_team else "plus"
    generation_kind = PAYMENT_LINK_GENERATION_TEAM if is_team else "plus_checkout"
    completed_at = _iso_timestamp(payload.get("completed_at"))
    output: dict[str, Any] = {
        "url": url,
        "plan": plan,
        "generation_kind": generation_kind,
        "plan_name": "chatgptteamplan" if is_team else "chatgptplusplan",
        "country": str(result.get("billing_country") or profile.get("country") or "").strip().upper(),
        "currency": str(result.get("currency") or profile.get("currency") or "").strip().upper(),
        "payment_link_format": "long_link",
        "payment_source": "long_link",
        "link_type": link_type,
        "profile_hash": profile_hash,
        "remote_batch_id": str(payload.get("batch_id") or "").strip(),
        "remote_job_id": str(payload.get("job_id") or "").strip(),
        "remote_request_id": str(payload.get("request_id") or "").strip(),
        "generated_at": completed_at,
        "created_at": completed_at or datetime.now(timezone.utc).isoformat(),
    }
    # UPI's QR deadline is the only expiry that is safe for QR cleanup.  The
    # upstream service returns the scalar ``link_expires_at`` and may also
    # include the nested SetupIntent shape; prefer the nested QR value whenever
    # it is present and retain its provenance for the account UI.
    qr_expires_at = extract_payment_link_qr_expires_at(result, payment_type=link_type)
    if qr_expires_at is None:
        qr_expires_at = extract_payment_link_qr_expires_at(payload, payment_type=link_type)
    expiry_source = normalize_payment_link_expiry_source(
        result.get("link_expiry_source") or payload.get("link_expiry_source"),
        link_type,
    )
    raw_expires_at = result.get("link_expires_at")
    if link_type == "upi":
        if qr_expires_at is not None:
            raw_expires_at = qr_expires_at
            expiry_source = "upi_qr_code"
        elif expiry_source == "checkout_session":
            raw_expires_at = None
        elif raw_expires_at not in (None, "") and not expiry_source:
            # Older internal API rows exposed the UPI QR scalar before adding
            # an explicit provenance field.  Accept only a five-minute-shaped
            # deadline so an untagged Checkout Session value cannot leak in.
            candidate_expiry = normalize_payment_link_expires_at(raw_expires_at)
            try:
                completed_epoch = int(float(payload.get("completed_at") or 0))
            except (TypeError, ValueError):
                completed_epoch = 0
            if (
                candidate_expiry is not None
                and completed_epoch > 0
                and candidate_expiry <= completed_epoch + UPI_QR_VALIDITY_SECONDS + UPI_QR_EXPIRY_TOLERANCE_SECONDS
            ):
                expiry_source = "upi_qr_code"
            else:
                raw_expires_at = None
    link_expires_at = normalize_payment_link_expires_at(
        raw_expires_at
    )
    if link_expires_at is not None:
        output["link_expires_at"] = link_expires_at
        if expiry_source:
            output["link_expiry_source"] = expiry_source
    if link_type == "paypal":
        output["paypal_url"] = _http_url(result.get("paypal_url")) or url
    if is_team:
        output["team_plan_data"] = team_plan_data
        output["workspace_name"] = team_plan_data.get("workspace_name") or ""
        output["price_interval"] = team_plan_data.get("price_interval") or "month"
        output["seat_quantity"] = team_plan_data.get("seat_quantity") or 2
        output["cancel_url"] = team_plan_data.get("cancel_url") or ""
        output["promo_code_digest"] = promo_code_digest
        output["checkout_proxy_region"] = checkout_proxy_region
        output["checkout_ui_mode"] = checkout_ui_mode or "hosted"
    for key in (
        "provider_redirect_url",
        "long_url",
        "stripe_redirect_url",
        "stripe_hosted_url",
        "cs_id",
        "payment_method_id",
        "payment_method_type",
        "processor_entity",
        "billing_country",
        "payment_locale",
        "amount",
        "amount_display",
        "cs_count",
    ):
        value = result.get(key)
        if value is not None and value != "":
            output[key] = value
    output["variant_key"] = (
        payment_link_variant_key(output)
        if is_team
        else str(result.get("variant_key") or "").strip() or payment_link_variant_key(output)
    )
    return output


class LongLinkPaymentClient:
    def __init__(
        self,
        *,
        base_url: str,
        api_key: str,
        request_timeout: float = DEFAULT_REQUEST_TIMEOUT_SECONDS,
        profile_cache_seconds: float = DEFAULT_PROFILE_CACHE_SECONDS,
        session: requests.Session | None = None,
        monotonic: Callable[[], float] = time.monotonic,
    ) -> None:
        self.base_url = normalize_long_link_base_url(base_url)
        self.api_key = str(api_key or "").strip()
        self.request_timeout = max(float(request_timeout or DEFAULT_REQUEST_TIMEOUT_SECONDS), 1.0)
        self.profile_cache_seconds = max(float(profile_cache_seconds or 0.0), 0.0)
        self.session = session or requests.Session()
        self._monotonic = monotonic
        self._api_mode: str | None = None
        self._api_mode_lock = threading.Lock()
        if not self.api_key:
            raise LongLinkPaymentError("未配置支付链接生成服务密钥")
        if len(self.api_key) > 512 or any(ord(character) < 32 or ord(character) == 127 for character in self.api_key):
            raise LongLinkPaymentError("支付链接生成服务密钥格式无效")

    @classmethod
    def from_runtime_config(cls) -> "LongLinkPaymentClient":
        """Build from shared/runtime config first, retaining environment fallbacks."""
        return cls(
            base_url=_runtime_config_value(
                "openai_pay_long_link_base_url",
                "OPENAI_PAY_LONG_LINK_BASE_URL",
                DEFAULT_BASE_URL,
            ),
            api_key=_runtime_config_value(
                "openai_pay_long_link_api_key",
                "OPENAI_PAY_LONG_LINK_API_KEY",
            ),
            request_timeout=_env_float(
                "OPENAI_PAY_LONG_LINK_REQUEST_TIMEOUT_SECONDS",
                DEFAULT_REQUEST_TIMEOUT_SECONDS,
                minimum=1.0,
            ),
            profile_cache_seconds=_env_float(
                "OPENAI_PAY_LONG_LINK_PROFILE_CACHE_SECONDS",
                DEFAULT_PROFILE_CACHE_SECONDS,
                minimum=0.0,
            ),
        )

    @classmethod
    def from_env(cls) -> "LongLinkPaymentClient":
        """Backward-compatible factory name used by existing task code."""

        return cls.from_runtime_config()

    @property
    def api_version(self) -> str:
        with self._api_mode_lock:
            return self._api_mode or _API_MODE_V1

    def _set_api_mode(self, mode: str) -> None:
        with self._api_mode_lock:
            self._api_mode = mode

    def _get_api_mode(self) -> str | None:
        with self._api_mode_lock:
            return self._api_mode

    def _cache_key(self, overrides: dict[str, Any] | None = None) -> tuple[str, str, str]:
        override_digest = ""
        if isinstance(overrides, dict) and overrides:
            try:
                import json

                override_digest = hashlib.sha256(
                    json.dumps(overrides, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode("utf-8")
                ).hexdigest()
            except (TypeError, ValueError):
                override_digest = hashlib.sha256(repr(sorted(overrides.items())).encode("utf-8")).hexdigest()
        return self.base_url, hashlib.sha256(self.api_key.encode("utf-8")).hexdigest(), override_digest

    def _request_once(
        self,
        method: str,
        path: str,
        *,
        api_mode: str,
        payload: dict[str, Any] | None = None,
        secrets: Iterable[str] = (),
        allow_not_found: bool = False,
    ) -> dict[str, Any] | None:
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
        if api_mode == _API_MODE_LEGACY:
            headers["X-Internal-API-Key"] = self.api_key
        else:
            headers["Authorization"] = f"Bearer {self.api_key}"
        try:
            response = self.session.request(
                method,
                f"{self.base_url}{path}",
                json=payload,
                headers=headers,
                timeout=self.request_timeout,
            )
        except requests.RequestException as exc:
            raise LongLinkPaymentError(
                f"支付链接生成服务不可用: {_safe_error_text(exc, secrets=(*secrets, self.api_key))}"
            ) from exc
        status_code = int(response.status_code or 0)
        if allow_not_found and status_code == 404:
            return None
        try:
            data = response.json()
        except ValueError as exc:
            raise LongLinkPaymentError(f"支付链接生成服务返回无效 JSON (HTTP {status_code})") from exc
        if not isinstance(data, dict):
            raise LongLinkPaymentError(f"支付链接生成服务返回格式错误 (HTTP {status_code})")
        if not 200 <= status_code < 300:
            detail = data.get("detail") or data.get("error") or data.get("message") or "上游请求失败"
            raise LongLinkPaymentError(
                f"支付链接生成服务请求失败 (HTTP {status_code}): "
                f"{_safe_error_text(detail, secrets=(*secrets, self.api_key))}"
            )
        return data

    def _request(
        self,
        method: str,
        v1_path: str,
        legacy_path: str,
        *,
        payload: dict[str, Any] | None = None,
        secrets: Iterable[str] = (),
    ) -> dict[str, Any]:
        mode = self._get_api_mode()
        if mode != _API_MODE_LEGACY:
            response = self._request_once(
                method,
                v1_path,
                api_mode=_API_MODE_V1,
                payload=payload,
                secrets=secrets,
                allow_not_found=mode is None,
            )
            if response is not None:
                self._set_api_mode(_API_MODE_V1)
                return response

        response = self._request_once(
            method,
            legacy_path,
            api_mode=_API_MODE_LEGACY,
            payload=payload,
            secrets=secrets,
        )
        if response is None:
            raise LongLinkPaymentError("支付链接生成服务未返回结果")
        self._set_api_mode(_API_MODE_LEGACY)
        return response

    def get_profile(
        self,
        *,
        overrides: dict[str, Any] | None = None,
        force_refresh: bool = False,
    ) -> dict[str, Any]:
        safe_overrides = dict(overrides) if isinstance(overrides, dict) else {}
        cache_key = self._cache_key(safe_overrides)
        now = self._monotonic()
        if not force_refresh and self.profile_cache_seconds > 0:
            with _profile_cache_lock:
                cached = _profile_cache.get(cache_key)
                if cached and cached[0] > now:
                    return dict(cached[1])
        if safe_overrides:
            normalized = normalize_payment_profile(
                self._request(
                    "POST",
                    _V1_PROFILE_PATH,
                    _LEGACY_PROFILE_PATH,
                    payload={"profileOverrides": safe_overrides},
                )
            )
        else:
            normalized = normalize_payment_profile(
                self._request("GET", _V1_PROFILE_PATH, _LEGACY_PROFILE_PATH)
            )
        if not normalized["profile_hash"]:
            raise LongLinkPaymentError("支付链接生成服务未返回 profile_hash")
        if self.profile_cache_seconds > 0:
            with _profile_cache_lock:
                _profile_cache[cache_key] = (now + self.profile_cache_seconds, dict(normalized))
        return normalized

    def submit_batch(
        self,
        *,
        items: list[dict[str, Any]],
        expected_profile_hash: str,
        profile_overrides: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        if not items:
            raise LongLinkPaymentError("支付链接批次不能为空")
        if len(items) > 1000:
            raise LongLinkPaymentError("单次最多提交 1000 个支付链接账号")
        serialized_items: list[dict[str, str]] = []
        tokens: list[str] = []
        seen_ids: set[str] = set()
        for item in items:
            raw = item if isinstance(item, dict) else {}
            token = str(raw.get("access_token") or raw.get("accessToken") or "").strip()
            request_id = str(raw.get("request_id") or raw.get("requestId") or "").strip()
            if not token:
                raise LongLinkPaymentError("账号缺少 Access Token")
            if not request_id:
                raise LongLinkPaymentError("支付链接请求缺少 request_id")
            if request_id in seen_ids:
                raise LongLinkPaymentError("同一批次存在重复 request_id")
            seen_ids.add(request_id)
            tokens.append(token)
            serialized_items.append({"accessToken": token, "requestId": request_id})
        request_payload: dict[str, Any] = {
            "expectedProfileHash": str(expected_profile_hash or "").strip(),
            "items": serialized_items,
        }
        if isinstance(profile_overrides, dict) and profile_overrides:
            request_payload["profileOverrides"] = dict(profile_overrides)
        response = self._request(
            "POST",
            _V1_BATCH_PATH,
            _LEGACY_BATCH_PATH,
            payload=request_payload,
            secrets=tokens,
        )
        returned_items = response.get("items") if isinstance(response.get("items"), list) else []
        if len(returned_items) != len(serialized_items):
            raise LongLinkPaymentError("支付链接生成服务未返回完整批次任务")
        returned_request_ids: set[str] = set()
        for item in returned_items:
            request_id = str(item.get("request_id") or "").strip() if isinstance(item, dict) else ""
            if not request_id or request_id in returned_request_ids:
                raise LongLinkPaymentError("支付链接生成服务返回了无效批次任务")
            returned_request_ids.add(request_id)
        expected_request_ids = {item["requestId"] for item in serialized_items}
        if returned_request_ids != expected_request_ids:
            raise LongLinkPaymentError("支付链接生成服务返回的批次任务与请求不一致")
        return response

    def get_batch(self, batch_id: str) -> dict[str, Any]:
        normalized_id = str(batch_id or "").strip()
        if not normalized_id:
            raise LongLinkPaymentError("支付链接远端批次 ID 为空")
        response = self._request(
            "GET",
            _V1_BATCH_STATUS_PATH.format(batch_id=urllib.parse.quote(normalized_id, safe="")),
            _LEGACY_BATCH_STATUS_PATH.format(batch_id=urllib.parse.quote(normalized_id, safe="")),
        )
        status = str(response.get("status") or "").strip().lower()
        if status not in _RUNNING_STATUSES | _TERMINAL_STATUSES | {"partial"}:
            raise LongLinkPaymentError(f"支付链接生成服务返回未知批次状态: {_safe_error_text(status)}")
        if not isinstance(response.get("items"), list):
            raise LongLinkPaymentError("支付链接生成服务未返回批次项目")
        return response


def clear_profile_cache() -> None:
    with _profile_cache_lock:
        _profile_cache.clear()
