"""Internal API client for PayPal links generated by openai-pay-long-link."""

from __future__ import annotations

import hashlib
import os
import re
import threading
import time
import urllib.parse
import uuid
from decimal import Decimal, InvalidOperation
from typing import Any, Callable

import requests


DEFAULT_BASE_URL = "http://openai-pay-long-link:8788"
DEFAULT_REQUEST_TIMEOUT_SECONDS = 20.0
DEFAULT_JOB_TIMEOUT_SECONDS = 1800.0
DEFAULT_POLL_INTERVAL_SECONDS = 2.0
DEFAULT_PROFILE_CACHE_SECONDS = 30.0

_PROFILE_PATH = "/api/internal/paypal/profile"
_START_PATH = "/api/internal/paypal/start"
_JOB_PATH = "/api/internal/paypal/jobs/{job_id}"
_TERMINAL_STATUSES = {"done", "error"}
_RUNNING_STATUSES = {"queued", "running"}
_JWT_RE = re.compile(r"\beyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+(?:\.[A-Za-z0-9_-]+)?\b")
_profile_cache_lock = threading.Lock()
_profile_cache: dict[tuple[str, str], tuple[float, dict[str, Any]]] = {}


class LongLinkPayPalError(RuntimeError):
    """Raised when the internal PayPal link API cannot complete a request."""


def _env_float(name: str, default: float, *, minimum: float) -> float:
    try:
        value = float(str(os.getenv(name) or default).strip())
    except (TypeError, ValueError):
        value = default
    return max(value, minimum)


def normalize_payment_profile(profile_response: dict[str, Any] | None) -> dict[str, Any]:
    response = profile_response if isinstance(profile_response, dict) else {}
    profile = response.get("profile") if isinstance(response.get("profile"), dict) else {}
    profile_hash = str(response.get("profile_hash") or profile.get("profile_hash") or "").strip()
    country = str(profile.get("billing_country") or profile.get("country") or "").strip().upper()
    currency = str(profile.get("currency") or "").strip().upper()
    return {
        "profile_hash": profile_hash,
        "link_type": "paypal",
        "country": country,
        "currency": currency,
        "profile": dict(profile),
    }


def is_paypal_approval_url(value: Any) -> bool:
    text = str(value or "").strip()
    if not text.lower().startswith(("http://", "https://")):
        return False
    try:
        parsed = urllib.parse.urlsplit(text)
    except ValueError:
        return False
    hostname = str(parsed.hostname or "").lower()
    if hostname != "paypal.com" and not hostname.endswith(".paypal.com"):
        return False
    query = urllib.parse.parse_qs(parsed.query)
    return "ba_token" in query or "/agreements/approve" in parsed.path.lower()


def _safe_error_text(value: Any, *, secrets: tuple[str, ...] = ()) -> str:
    text = str(value or "").strip()
    for secret in secrets:
        if secret:
            text = text.replace(secret, "***")
    text = _JWT_RE.sub("***", text)
    return text[:300]


class LongLinkPayPalClient:
    def __init__(
        self,
        *,
        base_url: str,
        api_key: str,
        request_timeout: float = DEFAULT_REQUEST_TIMEOUT_SECONDS,
        job_timeout: float = DEFAULT_JOB_TIMEOUT_SECONDS,
        poll_interval: float = DEFAULT_POLL_INTERVAL_SECONDS,
        profile_cache_seconds: float = DEFAULT_PROFILE_CACHE_SECONDS,
        session: requests.Session | None = None,
        sleep: Callable[[float], None] = time.sleep,
        monotonic: Callable[[], float] = time.monotonic,
    ) -> None:
        self.base_url = str(base_url or "").strip().rstrip("/")
        self.api_key = str(api_key or "").strip()
        self.request_timeout = max(float(request_timeout or DEFAULT_REQUEST_TIMEOUT_SECONDS), 1.0)
        self.job_timeout = max(float(job_timeout or DEFAULT_JOB_TIMEOUT_SECONDS), 1.0)
        self.poll_interval = max(float(poll_interval or 0.0), 0.0)
        self.profile_cache_seconds = max(float(profile_cache_seconds or 0.0), 0.0)
        self.session = session or requests.Session()
        self._sleep = sleep
        self._monotonic = monotonic
        if not self.base_url:
            raise LongLinkPayPalError("未配置 PayPal 提链接口地址")
        if not self.api_key:
            raise LongLinkPayPalError("未配置 PayPal 提链接口密钥")

    @classmethod
    def from_env(cls) -> "LongLinkPayPalClient":
        return cls(
            base_url=os.getenv("OPENAI_PAY_LONG_LINK_BASE_URL", DEFAULT_BASE_URL),
            api_key=os.getenv("OPENAI_PAY_LONG_LINK_API_KEY", ""),
            request_timeout=_env_float(
                "OPENAI_PAY_LONG_LINK_REQUEST_TIMEOUT_SECONDS",
                DEFAULT_REQUEST_TIMEOUT_SECONDS,
                minimum=1.0,
            ),
            job_timeout=_env_float(
                "OPENAI_PAY_LONG_LINK_JOB_TIMEOUT_SECONDS",
                DEFAULT_JOB_TIMEOUT_SECONDS,
                minimum=1.0,
            ),
            poll_interval=_env_float(
                "OPENAI_PAY_LONG_LINK_POLL_INTERVAL_SECONDS",
                DEFAULT_POLL_INTERVAL_SECONDS,
                minimum=0.1,
            ),
            profile_cache_seconds=_env_float(
                "OPENAI_PAY_LONG_LINK_PROFILE_CACHE_SECONDS",
                DEFAULT_PROFILE_CACHE_SECONDS,
                minimum=0.0,
            ),
        )

    def _cache_key(self) -> tuple[str, str]:
        key_hash = hashlib.sha256(self.api_key.encode("utf-8")).hexdigest()
        return self.base_url, key_hash

    def _request(
        self,
        method: str,
        path: str,
        *,
        payload: dict[str, Any] | None = None,
        secrets: tuple[str, ...] = (),
    ) -> dict[str, Any]:
        try:
            response = self.session.request(
                method,
                f"{self.base_url}{path}",
                json=payload,
                headers={
                    "Accept": "application/json",
                    "Content-Type": "application/json",
                    "X-Internal-API-Key": self.api_key,
                },
                timeout=self.request_timeout,
            )
        except requests.RequestException as exc:
            raise LongLinkPayPalError(f"PayPal 提链接口不可用: {_safe_error_text(exc, secrets=secrets)}") from exc

        try:
            data = response.json()
        except ValueError as exc:
            raise LongLinkPayPalError(f"PayPal 提链接口返回无效 JSON (HTTP {response.status_code})") from exc
        if not isinstance(data, dict):
            raise LongLinkPayPalError(f"PayPal 提链接口返回格式错误 (HTTP {response.status_code})")
        if not 200 <= int(response.status_code or 0) < 300:
            detail = data.get("detail") or data.get("error") or data.get("message") or "上游请求失败"
            raise LongLinkPayPalError(
                f"PayPal 提链接口请求失败 (HTTP {response.status_code}): "
                f"{_safe_error_text(detail, secrets=secrets)}"
            )
        return data

    def get_profile(self, *, force_refresh: bool = False) -> dict[str, Any]:
        cache_key = self._cache_key()
        now = self._monotonic()
        if not force_refresh and self.profile_cache_seconds > 0:
            with _profile_cache_lock:
                cached = _profile_cache.get(cache_key)
                if cached and cached[0] > now:
                    return dict(cached[1])

        response = self._request("GET", _PROFILE_PATH)
        normalized = normalize_payment_profile(response)
        if not normalized["profile_hash"]:
            raise LongLinkPayPalError("PayPal 提链接口未返回 profile_hash")
        if str(response.get("link_type") or "paypal").strip().lower() != "paypal":
            raise LongLinkPayPalError("PayPal 提链接口当前配置不是 paypal")
        if self.profile_cache_seconds > 0:
            with _profile_cache_lock:
                _profile_cache[cache_key] = (now + self.profile_cache_seconds, dict(normalized))
        return normalized

    def start(
        self,
        *,
        access_token: str,
        request_id: str,
        expected_profile_hash: str,
    ) -> dict[str, Any]:
        token = str(access_token or "").strip()
        if not token:
            raise LongLinkPayPalError("账号缺少 Access Token")
        resolved_request_id = str(request_id or "").strip() or f"auto-gpt:{uuid.uuid4().hex}"
        payload = {
            "access_token": token,
            "request_id": resolved_request_id,
            "expected_profile_hash": str(expected_profile_hash or "").strip(),
        }
        response = self._request("POST", _START_PATH, payload=payload, secrets=(token,))
        job_id = str(response.get("job_id") or "").strip()
        status = str(response.get("status") or "").strip().lower()
        if not job_id or status not in _RUNNING_STATUSES | _TERMINAL_STATUSES:
            raise LongLinkPayPalError("PayPal 提链接口未返回有效任务")
        return response

    def get_job(self, job_id: str, *, secrets: tuple[str, ...] = ()) -> dict[str, Any]:
        resolved_job_id = str(job_id or "").strip()
        if not resolved_job_id:
            raise LongLinkPayPalError("PayPal 提链接口任务 ID 为空")
        response = self._request(
            "GET",
            _JOB_PATH.format(job_id=urllib.parse.quote(resolved_job_id, safe="")),
            secrets=secrets,
        )
        status = str(response.get("status") or "").strip().lower()
        if status not in _RUNNING_STATUSES | _TERMINAL_STATUSES:
            raise LongLinkPayPalError(f"PayPal 提链接口返回未知任务状态: {_safe_error_text(status)}")
        return response

    def wait_for_job(self, job_id: str, *, secrets: tuple[str, ...] = ()) -> dict[str, Any]:
        deadline = self._monotonic() + self.job_timeout
        while True:
            job = self.get_job(job_id, secrets=secrets)
            status = str(job.get("status") or "").strip().lower()
            if status == "done":
                return job
            if status == "error":
                error = job.get("error") or "PayPal 链接生成失败"
                raise LongLinkPayPalError(_safe_error_text(error, secrets=secrets))
            if self._monotonic() >= deadline:
                raise LongLinkPayPalError(f"PayPal 链接生成超时，远端任务仍为 {status}")
            self._sleep(self.poll_interval)

    def generate_paypal_link(
        self,
        *,
        access_token: str,
        request_id: str = "",
        expected_profile_hash: str = "",
    ) -> dict[str, Any]:
        profile = self.get_profile()
        requested_profile_hash = str(expected_profile_hash or profile.get("profile_hash") or "").strip()
        start = self.start(
            access_token=access_token,
            request_id=request_id,
            expected_profile_hash=requested_profile_hash,
        )
        started_profile_hash = str(start.get("profile_hash") or "").strip()
        if started_profile_hash and started_profile_hash != requested_profile_hash:
            raise LongLinkPayPalError("PayPal 提链接口配置在任务启动前已变化")
        job = self.wait_for_job(str(start.get("job_id") or ""), secrets=(str(access_token or "").strip(),))
        job_profile_hash = str(job.get("profile_hash") or started_profile_hash or "").strip()
        if job_profile_hash != requested_profile_hash:
            raise LongLinkPayPalError("PayPal 提链接口任务 profile_hash 不匹配")
        result = job.get("result") if isinstance(job.get("result"), dict) else {}
        paypal_url = ""
        for key in ("paypal_url", "approval_url", "provider_redirect_url", "long_url"):
            candidate = str(result.get(key) or "").strip()
            if is_paypal_approval_url(candidate):
                paypal_url = candidate
                break
        if not paypal_url:
            raise LongLinkPayPalError("PayPal 提链接口任务成功但未返回有效 PayPal approval URL")

        output: dict[str, Any] = {
            "url": paypal_url,
            "paypal_url": paypal_url,
            "provider_redirect_url": str(result.get("provider_redirect_url") or paypal_url).strip(),
            "payment_link_format": "paypal_url",
            "payment_source": "long_link_paypal",
            "link_type": "paypal",
            "profile_hash": job_profile_hash,
            "country": str(profile.get("country") or "").strip().upper(),
            "currency": str(result.get("currency") or profile.get("currency") or "").strip().upper(),
            "remote_job_id": str(job.get("job_id") or start.get("job_id") or "").strip(),
            "remote_request_id": str(job.get("request_id") or start.get("request_id") or "").strip(),
        }
        for key in (
            "long_url",
            "stripe_redirect_url",
            "stripe_hosted_url",
            "cs_id",
            "payment_method_id",
            "payment_method_type",
            "processor_entity",
            "checkout_amount",
            "checkout_amount_is_zero",
            "amount",
            "amount_is_zero",
            "amount_display",
            "cs_count",
            "billing_country",
            "payment_locale",
        ):
            if key in result and result.get(key) is not None:
                output[key] = result.get(key)
        if "checkout_amount" not in output and "amount" in output:
            output["checkout_amount"] = output["amount"]
        if "checkout_amount_is_zero" not in output and "amount_is_zero" in output:
            output["checkout_amount_is_zero"] = bool(output["amount_is_zero"])
        if "checkout_amount_is_zero" not in output and "checkout_amount" in output:
            try:
                output["checkout_amount_is_zero"] = Decimal(str(output["checkout_amount"]).strip()) == 0
            except (InvalidOperation, TypeError, ValueError):
                pass
        return output


def clear_profile_cache() -> None:
    """Test/support hook for invalidating cached upstream profile snapshots."""
    with _profile_cache_lock:
        _profile_cache.clear()
